Fix botrole
Ignoring exception in member_join
Traceback (most recent call last):
  File "lib/discord/ext/commands/bot.py", line 252, in _run_extra
    yield from coro(*args, **kwargs)
  File "/Red-DiscordBot/cogs/welcomer.py", line 233, in on_member_join
    await self.bot.add_roles(member, roleobj[0])
TypeError: 'Role' object does not support indexing